name: deploy-storybook

on:
  push:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.15]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Deploy storybook - Exchange
        run: yarn storybook:deploy && echo $GH_TOKEN
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}